var num1 = 10;
var num2 = 16;
console.log("This is sum of num1 and num2");
console.log(num1 + num2);
console.log("This is subtraction of num1 and num2");
console.log(num1 - num2);
console.log("This is multiplication of num1 and num2");
console.log(num1 * num2);
console.log("This is division of num1 and num2");
console.log(num2 / num1);
console.log("This is decrement of num1");
var num3 = num1--;
console.log(num1);
var a = 2;
var b = 10;
var c = 15;
console.log(10 % 2);
console.log(c % a);
console.log(c % b);
